services:
  guacamole-guacd:
    image: guacamole/guacd
    networks:
      - guacamole_network
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  guacamole-postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_database
      POSTGRES_PASSWORD: 'Passw0rd!'
      POSTGRES_USER: db_user
    image: postgres:15.2-alpine
    networks:
      - guacamole_network
    restart: always
    volumes:
    - ./db_init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  guacamole:
    image: guacamole/guacamole
    group_add:
      - "1000"
    restart: always
    environment:
      GUACD_HOSTNAME: guacamole-guacd
      POSTGRESQL_HOSTNAME: guacamole-postgres
      POSTGRESQL_DATABASE: guacamole_database
      POSTGRESQL_USER: db_user
      POSTGRESQL_PASSWORD: 'Passw0rd!'
      RECORDING_SEARCH_PATH: /record
    networks:
      - guacamole_network
    volumes:
      - ./record:/record:rw
    ports:
      - 8080:8080/tcp 

networks:
  guacamole_network:
    driver: bridge